=== urban-stack/OpenZoning/data-standard/schema_vikranth/schema_district.json
{
  "$id": "District File Schema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "$comment": "Add a reference to constraints file",
  "properties": {
    "district": {
      "type": "object",
      "properties": {
        "identifier": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "districtType": {
          "type": "string",
          "enum": ["superDistrict", "base", "overlay1", "overlay2"]
        }
      },
      "required": ["identifier", "name"]
    },
    "last_updated": {
      "type": "string",
      "pattern": "^[0-9]{8}$"
    },
    "author": {
      "type": "string"
    },
    "usePermissions": {
      "type": "object",
      "properties": {
        "permitted": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "single-family",
              "two-family",
              "three-family",
              "intentional community",
              "Community residential facility, 0-16 people"
            ]
          }
        },
        "conditional": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "single-family",
              "two-family",
              "three-family",
              "multi-family",
              "cluster development"
            ]
          }
        }
      }
    },
    "accessoryStructuresPermissions": {
      "type": "object",
      "properties": {
        "allowedNumADs": {
          "type": "boolean"
        },
        "allowedTypesADs": {
          "type": "boolean"
        },
        "bulkOptionality": {
          "$ref": "schema_constraints object_final.json#/definitions/bulkOptionality"
        }
      }
    },
    "constraints": {
      "$ref": "schema_constraints object_final.json#/properties/constraints"
    }
  }
}

=== urban-stack/OpenZoning/data-standard/MVP/Minneapolis/Minneapolis_R2B_0.0.9_07212022.json
{
	"district": {
		"identifier": "MN-HennepinCo-Minneapolis-R2B",
		"name": "R2B Multiple-Family District",
		"districtType": "base",
    	"districtId": "R2B"
	},
	"last_updated": "20230815",
	"author": "OZFS Team",
	"usePermissions": {
		"permitted": ["single-family", "two-family", "three-family"]
	},
	"constraints": [
		{
			"constraintsModule": ["lotArea", "lotWidth"],
			"lot": {
				"developmentOptionalities": [
					{
						"developmentType": "primary/accessory",
			 			"bulkOptionalities": [
							{
								"bulks": ["one-family", "two-family", "three-family"],
								"lotArea": {
									"minimum": 5000,
									"maximum": 7500
								},
								"lotWidth": {
									"minimum": 40
								}
							}
						]
					}
				]
			}
		}
	]
}
